In [1]:
sentences = ["I ate dinner.", 
       "We had a three-course meal.", 
       "Brad came to dinner with us.",
       "He loves fish tacos.",
       "In the end, we all felt like we ate too much.",
       "We all agreed; it was a magnificent evening."]

1. setence transformer
2. langchain hugging
3. transformer

https://sbert.net/

In [3]:
!pip install -U sentence-transformers


  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 3.0.1
    Uninstalling sentence-transformers-3.0.1:
      Successfully uninstalled sentence-transformers-3.0.1


In [5]:
from sentence_transformers import  SentenceTransformer
import tqdm

In [6]:
model = SentenceTransformer('all-mpnet-base-v2')

/Users/hackthebox/Downloads/genai/genai/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [7]:
sentences[0]

'I ate dinner.'

In [8]:
model.encode(sentences[0])

array([-1.58598516e-02,  4.59825620e-02, -1.46350060e-02, -4.85908501e-02,
       -3.60325305e-03,  3.17664258e-02, -3.27771865e-02,  2.11894847e-02,
        1.07366787e-02,  2.50182487e-02,  1.58237591e-02,  1.24069704e-02,
        1.62089728e-02, -1.30434809e-02,  4.58447002e-02,  4.40269411e-02,
        4.57802117e-02, -4.32261918e-03,  1.87806804e-02,  5.22198016e-03,
       -1.86415780e-02, -7.11809983e-03,  3.01358793e-02,  1.70696080e-02,
       -1.53764151e-02,  3.34171690e-02, -6.55888626e-03,  1.58591345e-02,
        1.37039963e-02, -2.02766806e-02,  3.26632485e-02,  5.48362406e-03,
       -3.53351161e-02, -1.06665142e-01,  1.85711576e-06,  3.66638824e-02,
       -1.71335507e-02,  3.34468260e-02, -6.43021613e-02,  6.90796375e-02,
        2.50845645e-02,  2.89431270e-02, -8.98412894e-03, -1.84546318e-02,
        2.81152315e-02, -2.34797671e-02,  1.21612409e-02,  6.25150353e-02,
       -8.58703777e-02, -1.84623618e-03,  7.95865804e-03, -8.42522830e-02,
       -2.26104278e-02,  

In [9]:
model.encode(sentences[0]).shape

(768,)

In [10]:
!pip install langchain
!pip install langchain-community

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [11]:
from langchain.embeddings import HuggingFaceEmbeddings

In [12]:
embedding_model_name = "sentence-transformers/all-mpnet-base-v2"

In [13]:
model_kwargs = {"device": "cpu"}
embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name,model_kwargs=model_kwargs)

/Users/hackthebox/Downloads/genai/genai/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:141: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEmbeddings`.
  warn_deprecated(
/Users/hackthebox/Downloads/genai/genai/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [14]:
embedding_vector = embeddings.embed_query(sentences[0])

In [15]:
embedding_vector

[-0.015859851613640785,
 0.04598256200551987,
 -0.014635005965828896,
 -0.048590850085020065,
 -0.003603253047913313,
 0.03176642581820488,
 -0.03277718648314476,
 0.021189484745264053,
 0.01073667872697115,
 0.025018248707056046,
 0.015823759138584137,
 0.012406970374286175,
 0.01620897278189659,
 -0.013043480925261974,
 0.04584470018744469,
 0.0440269410610199,
 0.04578021168708801,
 -0.004322619177401066,
 0.018780680373311043,
 0.005221980158239603,
 -0.018641578033566475,
 -0.007118099834769964,
 0.030135879293084145,
 0.017069607973098755,
 -0.015376415103673935,
 0.033417169004678726,
 -0.0065588862635195255,
 0.01585913449525833,
 0.013703996315598488,
 -0.02027668058872223,
 0.0326632484793663,
 0.005483624059706926,
 -0.03533511608839035,
 -0.10666514188051224,
 1.8571157625046908e-06,
 0.036663882434368134,
 -0.017133550718426704,
 0.03344682604074478,
 -0.06430216133594513,
 0.06907963752746582,
 0.025084564462304115,
 0.028943127021193504,
 -0.008984128944575787,
 -0.01845

In [16]:
len(embedding_vector)

768

### one more approach with tranformer huggingface libary

In [17]:
import torch
from transformers import BertTokenizer, BertModel
import random

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
random_seed=42
random.seed(random_seed)
torch.manual_seed(random_seed)

In [19]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

/Users/hackthebox/Downloads/genai/genai/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [20]:
model=BertModel.from_pretrained("bert-base-uncased")

A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Pl

In [21]:
text="follow sunny for genai learning"

In [22]:
encoding=tokenizer.batch_encode_plus([text],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [23]:
input_ids=encoding["input_ids"]

In [24]:
attention_mask=encoding["attention_mask"]

In [25]:
with torch.no_grad():
  outputs=model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [26]:
word_embeddings

tensor([[[-0.0046, -0.1060, -0.0177,  ...,  0.0474,  0.0697,  0.2605],
         [ 0.8739, -0.1599,  0.5948,  ...,  0.4223,  0.2269, -0.1508],
         [ 0.0209, -0.3746, -0.2735,  ...,  0.3497,  0.0062, -0.4563],
         ...,
         [-0.2692, -0.4198, -0.1005,  ..., -0.0563, -0.2520, -0.6442],
         [-0.4552, -0.7338, -0.2614,  ...,  0.8366,  0.2496, -0.1972],
         [ 0.8920,  0.1769, -0.2345,  ...,  0.3265, -0.7962, -0.2090]]])

In [27]:
word_embeddings.shape

torch.Size([1, 8, 768])

In [28]:
input_ids[0]

tensor([  101,  3582, 11559,  2005,  8991,  4886,  4083,   102])

In [29]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [31]:
decode

'follow sunny for genai learning'